pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_FILE = '../docker-compose.yaml'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/aziz0220/Mini-Projet-Docker'
            }
        }
        stage('Run Docker Compose') {
            steps {
                script {
                    // Start Docker Compose for all services
                    sh 'docker compose -f ../docker-compose.yaml up -d'
                }
            }
        }
        stage('Stop Services') {
            steps {
                script {
                    // Stop all containers after tests
                    sh 'docker compose down'
                }
            }
        }
    }
    post {
        success {
            echo 'Build and tests successful!'
        }
        failure {
            echo 'Build or tests failed!'
        }
    }
}

